[[index]]
name = "quansight"
maintainers = [
    { name = "Michał Górny", email = "mgorny@quansight.com" },
    { name = "Ralf Gommers", email = "rgommers@quansight.com" },
]
registry = "https://pypi.anaconda.org/mgorny/simple/"
packages = [
    "numpy",
    "scikit-learn",
    "scipy"
]

[[index]]
name = "pytorch"
maintainers = [
    { name = "Andrey Talman", email = "atalman@meta.com" },
    { name = "Eli Uriegas", email = "eliuriegas@meta.com" },
]
registry = "https://download.pytorch.org/whl/variant/"
packages = [
    # NVIDIA Packages
    "nvidia-cublas",
    "nvidia-cuda-cupti",
    "nvidia-cuda-nvrtc",
    "nvidia-cuda-runtime",
    "nvidia-cudnn",
    "nvidia-cufft",
    "nvidia-cufile",
    "nvidia-curand",
    "nvidia-cusolver",
    "nvidia-cusparse",
    "nvidia-cusparselt",
    "nvidia-nccl",
    "nvidia-nvjitlink",
    "nvidia-nvtx",
    "nvidia-variant-provider",
    # PyTorch
    "torch",
    "torchvision"
]
