name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13" 
          
      - name: Install the package and test dependencies
        run: |
          uv sync --frozen

      - name: Build site
        run: |
          uv run main.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: build/
        
  # Deployment job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ github.token }}
